server:
  port: 8080
  error:
    include:
      message: true

spring:
  application:
    name: rangiffler-gateway

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
---
spring:
  config:
    activate:
      on-profile: 'local'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://127.0.0.1:9000'
grpc:
  client:
    grpcCountriesClient:
      address: 'static://127.0.0.1:9021'
      negotiationType: PLAINTEXT
    grpcPhotoClient:
      address: 'static://127.0.0.1:9031'
      max-inbound-message-size: 20971520
      negotiationType: PLAINTEXT

rangiffler-front:
  base-uri: 'http://127.0.0.1:3001'
rangiffler-userdata:
  base-uri: 'http://127.0.0.1:9010'
rangiffler-geo:
  base-uri: 'http://127.0.0.1:9020'
rangiffler-photos:
  base-uri: 'http://127.0.0.1:9030'
---
spring:
  config:
    activate:
      on-profile: 'docker'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://auth.rangiffler.dc:9000'
grpc:
  client:
    grpcCountriesClient:
      address: 'static://geo.rangiffler.dc:9021'
      negotiationType: PLAINTEXT
    grpcPhotoClient:
      address: 'static://photo.rangiffler.dc:9031'
      negotiationType: PLAINTEXT

rangiffler-photos:
  base-uri: 'http://photo.rangiffler.dc:9030'
rangiffler-users:
  base-uri: 'http://userdata.rangiffler.dc:9010'
rangiffler-geo:
  base-uri: 'http://geo.rangiffler.dc:9020'
rangiffler-front:
  base-uri: 'http://frontend.rangiffler.dc'