CREATE DATABASE IF NOT EXISTS `rangiffler-geo`;
USE `rangiffler-geo`;

create table if not exists countries
(
    id              BINARY(16)  unique not null default (UUID_TO_BIN(UUID(), TRUE)),
    country_name    varchar(50) unique not null,
    country_code    varchar(5) unique not null,
    primary key (id)
);

INSERT IGNORE INTO countries(country_name, country_code) values ('Fiji', 'FJ');
INSERT IGNORE INTO countries(country_name, country_code) values ('Tanzania', 'TZ');
INSERT IGNORE INTO countries(country_name, country_code) values ('Western Sahara', 'EH');
INSERT IGNORE INTO countries(country_name, country_code) values ('Canada', 'CA');
INSERT IGNORE INTO countries(country_name, country_code) values ('United States', 'US');
INSERT IGNORE INTO countries(country_name, country_code) values ('Kazakhstan', 'KZ');
INSERT IGNORE INTO countries(country_name, country_code) values ('Uzbekistan', 'UZ');
INSERT IGNORE INTO countries(country_name, country_code) values ('Papua New Guinea', 'PG');
INSERT IGNORE INTO countries(country_name, country_code) values ('Indonesia', 'ID');
INSERT IGNORE INTO countries(country_name, country_code) values ('Argentina', 'AR');
INSERT IGNORE INTO countries(country_name, country_code) values ('Chile', 'CL');
INSERT IGNORE INTO countries(country_name, country_code) values ('Democratic Republic of the Congo', 'CD');
INSERT IGNORE INTO countries(country_name, country_code) values ('Somalia', 'SO');
INSERT IGNORE INTO countries(country_name, country_code) values ('Kenya', 'KE');
INSERT IGNORE INTO countries(country_name, country_code) values ('Sudan', 'SD');
INSERT IGNORE INTO countries(country_name, country_code) values ('Chad', 'TD');
INSERT IGNORE INTO countries(country_name, country_code) values ('Haiti', 'HT');
INSERT IGNORE INTO countries(country_name, country_code) values ('Dominican Republic', 'DO');
INSERT IGNORE INTO countries(country_name, country_code) values ('Russia', 'RU');
INSERT IGNORE INTO countries(country_name, country_code) values ('Bahamas', 'BS');
INSERT IGNORE INTO countries(country_name, country_code) values ('Falkland Islands', 'FK');
INSERT IGNORE INTO countries(country_name, country_code) values ('Norway', 'NO');
INSERT IGNORE INTO countries(country_name, country_code) values ('Greenland', 'GL');
INSERT IGNORE INTO countries(country_name, country_code) values ('Timor-Leste', 'TL');
INSERT IGNORE INTO countries(country_name, country_code) values ('South Africa', 'ZA');
INSERT IGNORE INTO countries(country_name, country_code) values ('Lesotho', 'LS');
INSERT IGNORE INTO countries(country_name, country_code) values ('Mexico', 'MX');
INSERT IGNORE INTO countries(country_name, country_code) values ('Uruguay', 'UY');
INSERT IGNORE INTO countries(country_name, country_code) values ('Brazil', 'BR');
INSERT IGNORE INTO countries(country_name, country_code) values ('Bolivia', 'BO');
INSERT IGNORE INTO countries(country_name, country_code) values ('Peru', 'PE');
INSERT IGNORE INTO countries(country_name, country_code) values ('Colombia', 'CO');
INSERT IGNORE INTO countries(country_name, country_code) values ('Panama', 'PA');
INSERT IGNORE INTO countries(country_name, country_code) values ('Costa Rica', 'CR');
INSERT IGNORE INTO countries(country_name, country_code) values ('Nicaragua', 'NI');
INSERT IGNORE INTO countries(country_name, country_code) values ('Honduras', 'HN');
INSERT IGNORE INTO countries(country_name, country_code) values ('El Salvador', 'SV');
INSERT IGNORE INTO countries(country_name, country_code) values ('Guatemala', 'GT');
INSERT IGNORE INTO countries(country_name, country_code) values ('Belize', 'BZ');
INSERT IGNORE INTO countries(country_name, country_code) values ('Venezuela', 'VE');
INSERT IGNORE INTO countries(country_name, country_code) values ('Guyana', 'GY');
INSERT IGNORE INTO countries(country_name, country_code) values ('Suriname', 'SR');
INSERT IGNORE INTO countries(country_name, country_code) values ('France', 'FR');
INSERT IGNORE INTO countries(country_name, country_code) values ('Ecuador', 'EC');
INSERT IGNORE INTO countries(country_name, country_code) values ('Puerto Rico', 'PR');
INSERT IGNORE INTO countries(country_name, country_code) values ('Jamaica', 'JM');
INSERT IGNORE INTO countries(country_name, country_code) values ('Cuba', 'CU');
INSERT IGNORE INTO countries(country_name, country_code) values ('Zimbabwe', 'ZW');
INSERT IGNORE INTO countries(country_name, country_code) values ('Botswana', 'BW');
INSERT IGNORE INTO countries(country_name, country_code) values ('Namibia', 'NA');
INSERT IGNORE INTO countries(country_name, country_code) values ('Senegal', 'SN');
INSERT IGNORE INTO countries(country_name, country_code) values ('Mali', 'ML');
INSERT IGNORE INTO countries(country_name, country_code) values ('Mauritania', 'MR');
INSERT IGNORE INTO countries(country_name, country_code) values ('Benin', 'BJ');
INSERT IGNORE INTO countries(country_name, country_code) values ('Niger', 'NE');
INSERT IGNORE INTO countries(country_name, country_code) values ('Nigeria', 'NG');
INSERT IGNORE INTO countries(country_name, country_code) values ('Cameroon', 'CM');
INSERT IGNORE INTO countries(country_name, country_code) values ('Togo', 'TG');
INSERT IGNORE INTO countries(country_name, country_code) values ('Ghana', 'GH');
INSERT IGNORE INTO countries(country_name, country_code) values ('Côted''Ivoire', 'CI');
INSERT IGNORE INTO countries(country_name, country_code) values ('Guinea', 'GN');
INSERT IGNORE INTO countries(country_name, country_code) values ('Guinea-Bissau', 'GW');
INSERT IGNORE INTO countries(country_name, country_code) values ('Liberia', 'LR');
INSERT IGNORE INTO countries(country_name, country_code) values ('Sierra Leone', 'SL');
INSERT IGNORE INTO countries(country_name, country_code) values ('Burkina Faso', 'BF');
INSERT IGNORE INTO countries(country_name, country_code) values ('Central African Republic', 'CF');
INSERT IGNORE INTO countries(country_name, country_code) values ('Republic of the Congo', 'CG');
INSERT IGNORE INTO countries(country_name, country_code) values ('Gabon', 'GA');
INSERT IGNORE INTO countries(country_name, country_code) values ('Equatorial Guinea', 'GQ');
INSERT IGNORE INTO countries(country_name, country_code) values ('Zambia', 'ZM');
INSERT IGNORE INTO countries(country_name, country_code) values ('Malawi', 'MW');
INSERT IGNORE INTO countries(country_name, country_code) values ('Mozambique', 'MZ');
INSERT IGNORE INTO countries(country_name, country_code) values ('Eswatini', 'SZ');
INSERT IGNORE INTO countries(country_name, country_code) values ('Angola', 'AO');
INSERT IGNORE INTO countries(country_name, country_code) values ('Burundi', 'BI');
INSERT IGNORE INTO countries(country_name, country_code) values ('Israel', 'IL');
INSERT IGNORE INTO countries(country_name, country_code) values ('Lebanon', 'LB');
INSERT IGNORE INTO countries(country_name, country_code) values ('Madagascar', 'MG');
INSERT IGNORE INTO countries(country_name, country_code) values ('Palestine', 'PS');
INSERT IGNORE INTO countries(country_name, country_code) values ('The Gambia', 'GM');
INSERT IGNORE INTO countries(country_name, country_code) values ('Tunisia', 'TN');
INSERT IGNORE INTO countries(country_name, country_code) values ('Algeria', 'DZ');
INSERT IGNORE INTO countries(country_name, country_code) values ('Jordan', 'JO');
INSERT IGNORE INTO countries(country_name, country_code) values ('United Arab Emirates', 'AE');
INSERT IGNORE INTO countries(country_name, country_code) values ('Qatar', 'QA');
INSERT IGNORE INTO countries(country_name, country_code) values ('Kuwait', 'KW');
INSERT IGNORE INTO countries(country_name, country_code) values ('Iraq', 'IQ');
INSERT IGNORE INTO countries(country_name, country_code) values ('Oman', 'OM');
INSERT IGNORE INTO countries(country_name, country_code) values ('Vanuatu', 'VU');
INSERT IGNORE INTO countries(country_name, country_code) values ('Cambodia', 'KH');
INSERT IGNORE INTO countries(country_name, country_code) values ('Thailand', 'TH');
INSERT IGNORE INTO countries(country_name, country_code) values ('Lao PDR', 'LA');
INSERT IGNORE INTO countries(country_name, country_code) values ('Myanmar', 'MM');
INSERT IGNORE INTO countries(country_name, country_code) values ('Vietnam', 'VN');
INSERT IGNORE INTO countries(country_name, country_code) values ('Dem. Rep. Korea', 'KP');
INSERT IGNORE INTO countries(country_name, country_code) values ('Republic of Korea', 'KR');
INSERT IGNORE INTO countries(country_name, country_code) values ('Mongolia', 'MN');
INSERT IGNORE INTO countries(country_name, country_code) values ('India', 'IN');
INSERT IGNORE INTO countries(country_name, country_code) values ('Bangladesh', 'BD');
INSERT IGNORE INTO countries(country_name, country_code) values ('Bhutan', 'BT');
INSERT IGNORE INTO countries(country_name, country_code) values ('Nepal', 'NP');
INSERT IGNORE INTO countries(country_name, country_code) values ('Pakistan', 'PK');
INSERT IGNORE INTO countries(country_name, country_code) values ('Afghanistan', 'AF');
INSERT IGNORE INTO countries(country_name, country_code) values ('Tajikistan', 'TJ');
INSERT IGNORE INTO countries(country_name, country_code) values ('Kyrgyzstan', 'KG');
INSERT IGNORE INTO countries(country_name, country_code) values ('Turkmenistan', 'TM');
INSERT IGNORE INTO countries(country_name, country_code) values ('Iran', 'IR');
INSERT IGNORE INTO countries(country_name, country_code) values ('Syria', 'SY');
INSERT IGNORE INTO countries(country_name, country_code) values ('Armenia', 'AM');
INSERT IGNORE INTO countries(country_name, country_code) values ('Sweden', 'SE');
INSERT IGNORE INTO countries(country_name, country_code) values ('Belarus', 'BY');
INSERT IGNORE INTO countries(country_name, country_code) values ('Ukraine', 'UA');
INSERT IGNORE INTO countries(country_name, country_code) values ('Poland', 'PL');
INSERT IGNORE INTO countries(country_name, country_code) values ('Austria', 'AT');
INSERT IGNORE INTO countries(country_name, country_code) values ('Hungary', 'HU');
INSERT IGNORE INTO countries(country_name, country_code) values ('Moldova', 'MD');
INSERT IGNORE INTO countries(country_name, country_code) values ('Romania', 'RO');
INSERT IGNORE INTO countries(country_name, country_code) values ('Lithuania', 'LT');
INSERT IGNORE INTO countries(country_name, country_code) values ('Latvia', 'LV');
INSERT IGNORE INTO countries(country_name, country_code) values ('Estonia', 'EE');
INSERT IGNORE INTO countries(country_name, country_code) values ('Germany', 'DE');
INSERT IGNORE INTO countries(country_name, country_code) values ('Bulgaria', 'BG');
INSERT IGNORE INTO countries(country_name, country_code) values ('Greece', 'GR');
INSERT IGNORE INTO countries(country_name, country_code) values ('Turkey', 'TR');
INSERT IGNORE INTO countries(country_name, country_code) values ('Albania', 'AL');
INSERT IGNORE INTO countries(country_name, country_code) values ('Croatia', 'HR');
INSERT IGNORE INTO countries(country_name, country_code) values ('Switzerland', 'CH');
INSERT IGNORE INTO countries(country_name, country_code) values ('Luxembourg', 'LU');
INSERT IGNORE INTO countries(country_name, country_code) values ('Belgium', 'BE');
INSERT IGNORE INTO countries(country_name, country_code) values ('Netherlands', 'NL');
INSERT IGNORE INTO countries(country_name, country_code) values ('Portugal', 'PT');
INSERT IGNORE INTO countries(country_name, country_code) values ('Spain', 'ES');
INSERT IGNORE INTO countries(country_name, country_code) values ('Ireland', 'IE');
INSERT IGNORE INTO countries(country_name, country_code) values ('New Caledonia', 'NC');
INSERT IGNORE INTO countries(country_name, country_code) values ('Solomon Islands', 'SB');
INSERT IGNORE INTO countries(country_name, country_code) values ('New Zealand', 'NZ');
INSERT IGNORE INTO countries(country_name, country_code) values ('Australia', 'AU');
INSERT IGNORE INTO countries(country_name, country_code) values ('Sri Lanka', 'LK');
INSERT IGNORE INTO countries(country_name, country_code) values ('China', 'CN');
INSERT IGNORE INTO countries(country_name, country_code) values ('Taiwan', 'TW');
INSERT IGNORE INTO countries(country_name, country_code) values ('Italy', 'IT');
INSERT IGNORE INTO countries(country_name, country_code) values ('Denmark', 'DK');
INSERT IGNORE INTO countries(country_name, country_code) values ('United Kingdom', 'GB');
INSERT IGNORE INTO countries(country_name, country_code) values ('Iceland', 'IS');
INSERT IGNORE INTO countries(country_name, country_code) values ('Azerbaijan', 'AZ');
INSERT IGNORE INTO countries(country_name, country_code) values ('Georgia', 'GE');
INSERT IGNORE INTO countries(country_name, country_code) values ('Philippines', 'PH');
INSERT IGNORE INTO countries(country_name, country_code) values ('Malaysia', 'MY');
INSERT IGNORE INTO countries(country_name, country_code) values ('Brunei Darussalam', 'BN');
INSERT IGNORE INTO countries(country_name, country_code) values ('Slovenia', 'SI');
INSERT IGNORE INTO countries(country_name, country_code) values ('Finland', 'FI');
INSERT IGNORE INTO countries(country_name, country_code) values ('Slovakia', 'SK');
INSERT IGNORE INTO countries(country_name, country_code) values ('Czech Republic', 'CZ');
INSERT IGNORE INTO countries(country_name, country_code) values ('Eritrea', 'ER');
INSERT IGNORE INTO countries(country_name, country_code) values ('Japan', 'JP');
INSERT IGNORE INTO countries(country_name, country_code) values ('Paraguay', 'PY');
INSERT IGNORE INTO countries(country_name, country_code) values ('Yemen', 'YE');
INSERT IGNORE INTO countries(country_name, country_code) values ('Saudi Arabia', 'SA');
INSERT IGNORE INTO countries(country_name, country_code) values ('Northern Cyprus', 'CYP');
INSERT IGNORE INTO countries(country_name, country_code) values ('Cyprus', 'CY');
INSERT IGNORE INTO countries(country_name, country_code) values ('Morocco', 'MA');
INSERT IGNORE INTO countries(country_name, country_code) values ('Egypt', 'EG');
INSERT IGNORE INTO countries(country_name, country_code) values ('Libya', 'LY');
INSERT IGNORE INTO countries(country_name, country_code) values ('Ethiopia', 'ET');
INSERT IGNORE INTO countries(country_name, country_code) values ('Djibouti', 'DJ');
INSERT IGNORE INTO countries(country_name, country_code) values ('Somaliland', 'SOM');
INSERT IGNORE INTO countries(country_name, country_code) values ('Uganda', 'UG');
INSERT IGNORE INTO countries(country_name, country_code) values ('Rwanda', 'RW');
INSERT IGNORE INTO countries(country_name, country_code) values ('Bosnia and Herzegovina', 'BA');
INSERT IGNORE INTO countries(country_name, country_code) values ('Macedonia', 'MK');
INSERT IGNORE INTO countries(country_name, country_code) values ('Serbia', 'RS');
INSERT IGNORE INTO countries(country_name, country_code) values ('Montenegro', 'ME');
INSERT IGNORE INTO countries(country_name, country_code) values ('Kosovo', 'XK');
INSERT IGNORE INTO countries(country_name, country_code) values ('Trinidad and Tobago', 'TT');
INSERT IGNORE INTO countries(country_name, country_code) values ('South Sudan', 'SS');